---
repos:
  # Meta hooks to check the pre-commit config itself
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # General purpose hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: no-commit-to-branch
      - id: mixed-line-ending
        args: [--fix=lf]

  # Check markdown files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: c8fd5003603dd6f12447314ecd935ba87c09aff5  # frozen: v0.46.0
    hooks:
      - id: markdownlint

  # Check for common misspellings 1.
  - repo: https://github.com/crate-ci/typos
    rev: b67d1be06b53c7a9ecb6254ee4643e179800df72  # frozen: typos-dict-v0.13.11
    hooks:
      - id: typos
        args: []
        types: [markdown]

  # Check for common misspellings 2.
  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac  # frozen: v2.4.1
    hooks:
      - id: codespell
